wandb_version: 1

epochs:
  desc: null
  value: 11
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688909705.226943
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 1
      - 3
      - 5
